// <auto-generated />
using CustSurveyMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustSurveyMVC.Migrations
{
    [DbContext(typeof(TechSupportContext))]
    [Migration("20250413223232_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustSurveyMVC.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Address = "PO Box 96621",
                            City = "Washington",
                            Email = "ania@mma.nidc.com",
                            Name = "Ania Irvin",
                            Phone = "(301) 555-8950",
                            State = "DC"
                        },
                        new
                        {
                            CustomerID = 2,
                            Address = "1990 Westwood Blvd Ste 260",
                            City = "Los Angeles",
                            Email = "kenzie@mma.jobtrak.com",
                            Name = "Kenzie Quinn",
                            Phone = "(800) 555-8725",
                            State = "CA"
                        },
                        new
                        {
                            CustomerID = 3,
                            Address = "3255 Ramos Cir",
                            City = "Sacramento",
                            Email = "amauro@mma.ccc.org",
                            Name = "Anton Mauro",
                            Phone = "(916) 555-6670",
                            State = "CA"
                        },
                        new
                        {
                            CustomerID = 4,
                            Address = "Box 52001",
                            City = "San Francisco",
                            Email = "kanthoni@mma.pge.com",
                            Name = "Kaitlyn Anthoni",
                            Phone = "(800) 555-6081",
                            State = "CA"
                        },
                        new
                        {
                            CustomerID = 5,
                            Address = "7700 Forsyth",
                            City = "St Louis",
                            Email = "malia@mma.TheLibraryLtd.com",
                            Name = "Malia Marques",
                            Phone = "(314) 555-8834",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 6,
                            Address = "1555 W Lane Ave",
                            City = "Columbus",
                            Email = "Emily@mma.MicroCenter.com",
                            Name = "Emily Evan",
                            Phone = "(614) 555-4435",
                            State = "OH"
                        },
                        new
                        {
                            CustomerID = 7,
                            Address = "12 Daniel Road",
                            City = "Fairfield",
                            Email = "Ingrid@mma.richadvertizing.com",
                            Name = "Ingrid Neil",
                            Phone = "(201) 555-9742",
                            State = "NJ"
                        },
                        new
                        {
                            CustomerID = 8,
                            Address = "1483 Chain Bridge Rd, Ste 202",
                            City = "Mclean",
                            Email = "eLawrence@mma.ecomm.com",
                            Name = "Eileen Lawrence",
                            Phone = "eLawrence@mma.ecomm.com",
                            State = "VA"
                        },
                        new
                        {
                            CustomerID = 9,
                            Address = "PO Box 31",
                            City = "East Brunswick",
                            Email = "messence@mma.rrbowker.com",
                            Name = "Marjorie Essence",
                            Phone = "(800) 555-8110",
                            State = "NJ"
                        },
                        new
                        {
                            CustomerID = 10,
                            Address = "60 Madison Ave",
                            City = "New York",
                            Email = "tneftaly@mma.venture.com",
                            Name = "Thalia Neftaly",
                            Phone = "(212) 555-4800",
                            State = "NY"
                        },
                        new
                        {
                            CustomerID = 11,
                            Address = "PO Box 7028",
                            City = "St Louis",
                            Email = "harley@mma.cprinting.com",
                            Name = "Harley Myles",
                            Phone = "(301) 555-1494",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 12,
                            Address = "PO Box 39046",
                            City = "Minneapolis",
                            Email = "jmaxwell@mma.ccredit.com",
                            Name = "Jayda Maxwell",
                            Phone = "(612) 555-0057",
                            State = "MN"
                        });
                });

            modelBuilder.Entity("CustSurveyMVC.Models.Survey", b =>
                {
                    b.Property<int>("SurveyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyID"));

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int>("Efficiency")
                        .HasColumnType("int");

                    b.Property<int>("Resolution")
                        .HasColumnType("int");

                    b.Property<int>("Response")
                        .HasColumnType("int");

                    b.HasKey("SurveyID");

                    b.ToTable("Surveys");
                });
#pragma warning restore 612, 618
        }
    }
}
