// <auto-generated />
using CustomerListMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerListMVC.Migrations
{
    [DbContext(typeof(HalloweenContext))]
    [Migration("20230501132945_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerListMVC.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Email = "PaulPlodder@student.swic.edu",
                            FirstName = "Paul",
                            LastName = "Plodder",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 2,
                            Email = "GeorgeArfuss@student.swic.edu",
                            FirstName = "George",
                            LastName = "Arfuss",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 3,
                            Email = "TomTurtle@student.swic.edu",
                            FirstName = "Tom",
                            LastName = "Turtle",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 4,
                            Email = "WilliamJones@student.swic.edu",
                            FirstName = "William",
                            LastName = "Jones",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 5,
                            Email = "JohnJones@student.swic.edu",
                            FirstName = "John",
                            LastName = "Jones",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 6,
                            Email = "AnthonyJones@student.swic.edu",
                            FirstName = "Anthony",
                            LastName = "Jones",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 7,
                            Email = "KyleJones@student.swic.edu",
                            FirstName = "Kyle",
                            LastName = "Jones",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 8,
                            Email = "KelleyBerty@student.swic.edu",
                            FirstName = "Kelley",
                            LastName = "Berty",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 9,
                            Email = "GeorgeMacElroy@student.swic.edu",
                            FirstName = "George",
                            LastName = "MacElroy",
                            State = "IL"
                        },
                        new
                        {
                            CustomerID = 10,
                            Email = "JamesMcDunnel@student.swic.edu",
                            FirstName = "James",
                            LastName = "McDunnel",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 11,
                            Email = "ThomasMcDunnel@student.swic.edu",
                            FirstName = "Thomas",
                            LastName = "McDunnel",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 12,
                            Email = "ThomasSmith@student.swic.edu",
                            FirstName = "Thomas",
                            LastName = "Smith",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 13,
                            Email = "MartinJukes@student.swic.edu",
                            FirstName = "Martin",
                            LastName = "Jukes",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 14,
                            Email = "AugustSmith@student.swic.edu",
                            FirstName = "August",
                            LastName = "Smith",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 15,
                            Email = "RichardArfuss@student.swic.edu",
                            FirstName = "Richard",
                            LastName = "Arfuss",
                            State = "IL"
                        },
                        new
                        {
                            CustomerID = 16,
                            Email = "SeanArfuss@student.swic.edu",
                            FirstName = "Sean",
                            LastName = "Arfuss",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 17,
                            Email = "ArthurMueller@student.swic.edu",
                            FirstName = "Arthur",
                            LastName = "Mueller",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 18,
                            Email = "JamesMiller@student.swic.edu",
                            FirstName = "James",
                            LastName = "Miller",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 19,
                            Email = "DanielMueller@student.swic.edu",
                            FirstName = "Daniel",
                            LastName = "Mueller",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 20,
                            Email = "ThomasSmith@student.swic.edu",
                            FirstName = "Thomas",
                            LastName = "Smith",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 21,
                            Email = "MichaelMilkwagin@student.swic.edu",
                            FirstName = "Michael",
                            LastName = "Milkwagin",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 22,
                            Email = "MichaelNeuner@student.swic.edu",
                            FirstName = "Michael",
                            LastName = "Neuner",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 23,
                            Email = "KennOrtega@student.swic.edu",
                            FirstName = "Kenn",
                            LastName = "Ortega",
                            State = "IL"
                        },
                        new
                        {
                            CustomerID = 24,
                            Email = "PhilWill@student.swic.edu",
                            FirstName = "Phil",
                            LastName = "Will",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 25,
                            Email = "SallySellum@student.swic.edu",
                            FirstName = "Sally",
                            LastName = "Sellum",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 26,
                            Email = "BarneyVarfuss@student.swic.edu",
                            FirstName = "Barney",
                            LastName = "Varfuss",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 27,
                            Email = "JosephTummyfill@student.swic.edu",
                            FirstName = "Joseph",
                            LastName = "Tummyfill",
                            State = "Mo"
                        },
                        new
                        {
                            CustomerID = 28,
                            Email = "SteveRockford@student.swic.edu",
                            FirstName = "Steve",
                            LastName = "Rockford",
                            State = "IL"
                        },
                        new
                        {
                            CustomerID = 29,
                            Email = "DanielDaly@student.swic.edu",
                            FirstName = "Daniel",
                            LastName = "Daly",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 30,
                            Email = "SalvatoreMalt@student.swic.edu",
                            FirstName = "Salvatore",
                            LastName = "Malt",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 31,
                            Email = "RichardSmythe@student.swic.edu",
                            FirstName = "Richard",
                            LastName = "Smythe",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 32,
                            Email = "ThomasSmiley@student.swic.edu",
                            FirstName = "Thomas",
                            LastName = "Smiley",
                            State = "IL"
                        },
                        new
                        {
                            CustomerID = 33,
                            Email = "GeorgeRockford@student.swic.edu",
                            FirstName = "George",
                            LastName = "Rockford",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 34,
                            Email = "JeffreyFawlty@student.swic.edu",
                            FirstName = "Jeffrey",
                            LastName = "Fawlty",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 35,
                            Email = "DanielSteadman@student.swic.edu",
                            FirstName = "Daniel",
                            LastName = "Steadman",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 36,
                            Email = "GregoryJones@student.swic.edu",
                            FirstName = "Gregory",
                            LastName = "Jones",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 37,
                            Email = "GregoryEliot@student.swic.edu",
                            FirstName = "Gregory",
                            LastName = "Eliot",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 38,
                            Email = "JeffreyWillow@student.swic.edu",
                            FirstName = "Jeffrey",
                            LastName = "Willow",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 39,
                            Email = "RobertStiner@student.swic.edu",
                            FirstName = "Robert",
                            LastName = "Stiner",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 40,
                            Email = "LawrenceNessman@student.swic.edu",
                            FirstName = "Lawrence",
                            LastName = "Nessman",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 41,
                            Email = "RobertSulley@student.swic.edu",
                            FirstName = "Robert",
                            LastName = "Sulley",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 42,
                            Email = "LeonardBirdwall@student.swic.edu",
                            FirstName = "Leonard",
                            LastName = "Birdwall",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 43,
                            Email = "TerryKubick@student.swic.edu",
                            FirstName = "Terry",
                            LastName = "Kubick",
                            State = "IL"
                        },
                        new
                        {
                            CustomerID = 44,
                            Email = "JamesWebster@student.swic.edu",
                            FirstName = "James",
                            LastName = "Webster",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 45,
                            Email = "ArthurWaffles@student.swic.edu",
                            FirstName = "Arthur",
                            LastName = "Waffles",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 46,
                            Email = "MerrellVarfuss@student.swic.edu",
                            FirstName = "Merrell",
                            LastName = "Varfuss",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 47,
                            Email = "JamesWilliams@student.swic.edu",
                            FirstName = "James",
                            LastName = "Williams",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 48,
                            Email = "RobertWalleye@student.swic.edu",
                            FirstName = "Robert",
                            LastName = "Walleye",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 49,
                            Email = "KennyFeltz@student.swic.edu",
                            FirstName = "Kenny",
                            LastName = "Feltz",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 50,
                            Email = "AndrewVarfuss@student.swic.edu",
                            FirstName = "Andrew",
                            LastName = "Varfuss",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 51,
                            Email = "TerryFitzgerald@student.swic.edu",
                            FirstName = "Terry",
                            LastName = "Fitzgerald",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 52,
                            Email = "LawrenceWiner@student.swic.edu",
                            FirstName = "Lawrence",
                            LastName = "Winer",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 53,
                            Email = "SteveMaverick@student.swic.edu",
                            FirstName = "Steve",
                            LastName = "Maverick",
                            State = "IL"
                        },
                        new
                        {
                            CustomerID = 54,
                            Email = "KarlKong@student.swic.edu",
                            FirstName = "Karl",
                            LastName = "Kong",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 55,
                            Email = "JosephWiliams@student.swic.edu",
                            FirstName = "Joseph",
                            LastName = "Wiliams",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 56,
                            Email = "JulesBilliard@student.swic.edu",
                            FirstName = "Jules",
                            LastName = "Billiard",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 57,
                            Email = "MichaelSmith@student.swic.edu",
                            FirstName = "Michael",
                            LastName = "Smith",
                            State = "IL"
                        },
                        new
                        {
                            CustomerID = 58,
                            Email = "JosephJones@student.swic.edu",
                            FirstName = "Joseph",
                            LastName = "Jones",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 59,
                            Email = "JamesCaline@student.swic.edu",
                            FirstName = "James",
                            LastName = "Caline",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 60,
                            Email = "KevinPlodder@student.swic.edu",
                            FirstName = "Kevin",
                            LastName = "Plodder",
                            State = "MO"
                        },
                        new
                        {
                            CustomerID = 61,
                            Email = "KimTaylor@student.swic.edu",
                            FirstName = "Kim",
                            LastName = "Taylor",
                            State = "MO"
                        });
                });

            modelBuilder.Entity("CustomerListMVC.Models.State", b =>
                {
                    b.Property<string>("StateID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateID");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateID = "AK",
                            StateName = "Alaska"
                        },
                        new
                        {
                            StateID = "AL",
                            StateName = "Alabama"
                        },
                        new
                        {
                            StateID = "AR",
                            StateName = "Arkansas"
                        },
                        new
                        {
                            StateID = "AZ",
                            StateName = "Arizona"
                        },
                        new
                        {
                            StateID = "CA",
                            StateName = "California"
                        },
                        new
                        {
                            StateID = "CO",
                            StateName = "Colorado"
                        },
                        new
                        {
                            StateID = "CT",
                            StateName = "Connecticut"
                        },
                        new
                        {
                            StateID = "DC",
                            StateName = "District of Columbia"
                        },
                        new
                        {
                            StateID = "DE",
                            StateName = "Delaware"
                        },
                        new
                        {
                            StateID = "FL",
                            StateName = "Florida"
                        },
                        new
                        {
                            StateID = "GA",
                            StateName = "Georgia"
                        },
                        new
                        {
                            StateID = "HI",
                            StateName = "Hawaii"
                        },
                        new
                        {
                            StateID = "IA",
                            StateName = "Iowa"
                        },
                        new
                        {
                            StateID = "ID",
                            StateName = "Idaho"
                        },
                        new
                        {
                            StateID = "IL",
                            StateName = "Illinois"
                        },
                        new
                        {
                            StateID = "IN",
                            StateName = "Indiana"
                        },
                        new
                        {
                            StateID = "KS",
                            StateName = "Kansas"
                        },
                        new
                        {
                            StateID = "KY",
                            StateName = "Kentucky"
                        },
                        new
                        {
                            StateID = "LA",
                            StateName = "Lousiana"
                        },
                        new
                        {
                            StateID = "MA",
                            StateName = "Massachusetts"
                        },
                        new
                        {
                            StateID = "MD",
                            StateName = "Maryland"
                        },
                        new
                        {
                            StateID = "ME",
                            StateName = "Maine"
                        },
                        new
                        {
                            StateID = "MI",
                            StateName = "Michigan"
                        },
                        new
                        {
                            StateID = "MN",
                            StateName = "Minnesota"
                        },
                        new
                        {
                            StateID = "MO",
                            StateName = "Missouri"
                        },
                        new
                        {
                            StateID = "MS",
                            StateName = "Mississippi"
                        },
                        new
                        {
                            StateID = "MT",
                            StateName = "Montana"
                        },
                        new
                        {
                            StateID = "NC",
                            StateName = "North Carolina"
                        },
                        new
                        {
                            StateID = "ND",
                            StateName = "North Dakota"
                        },
                        new
                        {
                            StateID = "NE",
                            StateName = "Nebraska"
                        },
                        new
                        {
                            StateID = "NH",
                            StateName = "New Hampshire"
                        },
                        new
                        {
                            StateID = "NJ",
                            StateName = "New Jersey"
                        },
                        new
                        {
                            StateID = "NM",
                            StateName = "New Mexico"
                        },
                        new
                        {
                            StateID = "NV",
                            StateName = "Nevada"
                        },
                        new
                        {
                            StateID = "NY",
                            StateName = "New York"
                        },
                        new
                        {
                            StateID = "OH",
                            StateName = "Ohio"
                        },
                        new
                        {
                            StateID = "OK",
                            StateName = "Oklahoma"
                        },
                        new
                        {
                            StateID = "OR",
                            StateName = "Oregon"
                        },
                        new
                        {
                            StateID = "PA",
                            StateName = "Pennsylvania"
                        },
                        new
                        {
                            StateID = "RI",
                            StateName = "Rhode Island"
                        },
                        new
                        {
                            StateID = "SC",
                            StateName = "South Carolina"
                        },
                        new
                        {
                            StateID = "SD",
                            StateName = "South Dakota"
                        },
                        new
                        {
                            StateID = "TN",
                            StateName = "Tennessee"
                        },
                        new
                        {
                            StateID = "TX",
                            StateName = "Texas"
                        },
                        new
                        {
                            StateID = "UT",
                            StateName = "Utah"
                        },
                        new
                        {
                            StateID = "VA",
                            StateName = "Virginia"
                        },
                        new
                        {
                            StateID = "VI",
                            StateName = "Virgin Islands"
                        },
                        new
                        {
                            StateID = "VT",
                            StateName = "Vermont"
                        },
                        new
                        {
                            StateID = "WA",
                            StateName = "Washington"
                        },
                        new
                        {
                            StateID = "WI",
                            StateName = "Wisconsin"
                        },
                        new
                        {
                            StateID = "WV",
                            StateName = "West Virginia"
                        },
                        new
                        {
                            StateID = "WY",
                            StateName = "Wyoming"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
